source 'https://rubygems.org'

gem 'byebug'
gem 'eventmachine', '1.2.5'
gem 'pi_piper'
gem 'racksh'
gem 'rake'
gem 'sinatra'
gem 'sinatra-activerecord'
gem 'sinatra-contrib'
gem 'sinatra-param'
gem 'sqlite3'
